### ISSUE TITLE
Conditional statement to handle Invalid token 

### ISSUE THREAD

**Issue by ariebrainware** [andromedaorg/galonku-backend#25]
This statement doesn't produce any error, even if the token is invalid

https://github.com/andromedaorg/galonku-backend/blob/b8666453b359d2208993edf4b6dfe7262586deec/api/auth/auth-token/index.js#L15

@mhaidarh @michaeltamsil

**Comment by michaeltamsil** [comment]
check is ``` token ``` have value & the value is right
check is ``` process.env.JWT_SECRET ``` have value & the value is right

**Comment by michaeltamsil** [comment]
try to print out ``` console.log(error) ``` to see what value is

**Comment by mhaidarh** [comment]
Yes, check again if the `token` and `process.env.JWT_SECRET` are declared correctly.

https://github.com/andromedaorg/galonku-backend/blob/b8666453b359d2208993edf4b6dfe7262586deec/api/auth/auth-token/index.js#L11-L12

**Comment by mhaidarh** [comment]
It's better to check the `token` again that retrieved from headers, before `jwt.verify`.

**Comment by ariebrainware** [comment]
ok i'll try to fix typo first

**Comment by ariebrainware** [comment]
If token error:
![image](https://user-images.githubusercontent.com/26453961/44728063-ba162600-ab05-11e8-89e9-18528acf9c22.png)

![token-error](https://user-images.githubusercontent.com/26453961/44728189-05c8cf80-ab06-11e8-8b95-cfa9ee12b42c.png)
