### ISSUE TITLE
Sequelize not found when running Travis testing

### ISSUE THREAD

**Issue by ariebrainware** [andromedaorg/galonku-backend#30]
Can you give some review for this script, because I want to run testing on Travis CI and still face bug said: sequelize not found

https://github.com/andromedaorg/galonku-
backend/blob/5e73eaecafdf3f496e24397c1b9adc9b13cb7c0c/package.json#L6-L18

![screencapture-travis-ci-org-andromedaorg-galonku-backend-jobs-421928287-2018-08-29-14_11_29](https://user-images.githubusercontent.com/26453961/44771549-7d920b00-ab95-11e8-905d-f4f1867b37f7.png)

@mhaidarh @michaeltamsil

**Comment by michaeltamsil** [comment]
https://github.com/sequelize/cli/issues/119

**Comment by mhaidarh** [comment]
`yarn add --dev sequelize-cli`
